### ISSUE TITLE
Rework how to can-import the animations

### ISSUE THREAD

**Issue by mickmcgrath13** [mickmcgrath13/can-stache-animate#14]
it feels like the most laborious part of the API (`animationsModule.default.animations.shake`) is also the part you would use the most, so getting that down to `animations.shake` would be cool.

Maybe we could use something like:
`{^value.default.animations}="*animations"`

**Comment by chasenlehara** [comment]
`{^value.animations}="*animations"` is ok (after getting rid of `default` when [moving to ES5](https://github.com/mickmcgrath13/can-stache-animate/issues/13)), although my vote would be to export the `animations` as the module’s value and add the additional methods on it, so it would look something like this:


```js
import canStacheAnimations from 'can-stache-animations';
// canStacheAnimations is an array of animations so you can write `{^value}="*animations"`
canStacheAnimations.register();// Accept a list of animations, e.g. register({}, {})
canStacheAnimations.setDefaults();// Accept an object, e.g. setDefaults({duration: 500})
```

**Comment by mickmcgrath13** [comment]
@chasenlehara I'm a little hesitant to go that route because we need to import an object so that we can directly call a value.  For example, to add a 'shake' animation to a div, we currently do something like this:
```
<div (. someProp)="*animations.shake" />
```
..it's not really clear to me how that would look if `animations` were an array.

..then, if it's the case that it's an object, there is a slight possibility that people could name their animations as one of the named functions (like `register`, `setDefaults`, etc).

I'm open to the idea of making the import syntax more succinct, though.  I think what I'd like to do now is go ahead and merge https://github.com/mickmcgrath13/can-stache-animate/pull/21 to close this issue and create another issue to revisit the import syntax succinctness once more of can-stache-animate is up and running.

**Comment by mickmcgrath13** [comment]
https://github.com/mickmcgrath13/can-stache-animate/issues/22
